// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: distq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	// A Completed report that was recorded.
	Outcome_OUTCOME_ACCEPTED Outcome = 1
	// Refused: the job was not this worker's to finish any more.
	Outcome_OUTCOME_REFUSED Outcome = 2
	// A Failed report that was queued for another attempt.
	Outcome_OUTCOME_RETRYING Outcome = 3
	// A Failed report whose job exhausted its retries and is in the DLQ.
	Outcome_OUTCOME_DEAD_LETTERED Outcome = 4
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_ACCEPTED",
		2: "OUTCOME_REFUSED",
		3: "OUTCOME_RETRYING",
		4: "OUTCOME_DEAD_LETTERED",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":   0,
		"OUTCOME_ACCEPTED":      1,
		"OUTCOME_REFUSED":       2,
		"OUTCOME_RETRYING":      3,
		"OUTCOME_DEAD_LETTERED": 4,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_distq_proto_enumTypes[0].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_distq_proto_enumTypes[0]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{0}
}

// Core Job structure representing a background task
type Job struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type    string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Status  string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error   string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Retry bookkeeping — the server owns these, the worker only reads them.
	RetryCount    int32 `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    int32 `protobuf:"varint,7,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_distq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Job) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Job) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

// Enqueue RPC structures
type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_distq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_distq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EnqueueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// WorkerMessage is everything a worker sends up its stream.
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_Completed
	//	*WorkerMessage_Failed
	Message       isWorkerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_distq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerMessage) GetMessage() isWorkerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetCompleted() *Completed {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *WorkerMessage) GetFailed() *Failed {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

type isWorkerMessage_Message interface {
	isWorkerMessage_Message()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_Completed struct {
	Completed *Completed `protobuf:"bytes,3,opt,name=completed,proto3,oneof"`
}

type WorkerMessage_Failed struct {
	Failed *Failed `protobuf:"bytes,4,opt,name=failed,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Message() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Message() {}

func (*WorkerMessage_Completed) isWorkerMessage_Message() {}

func (*WorkerMessage_Failed) isWorkerMessage_Message() {}

// Hello opens the stream and names the worker. Every job this stream is given is
// leased to that id, and only that id may report on it.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_distq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// Heartbeat says "still working on this job": the server pushes the lease expiry
// forward, and answers with Lost if the job has already moved on.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_distq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Completed is the worker's verdict on a job that succeeded.
type Completed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completed) Reset() {
	*x = Completed{}
	mi := &file_distq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completed) ProtoMessage() {}

func (x *Completed) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completed.ProtoReflect.Descriptor instead.
func (*Completed) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{6}
}

func (x *Completed) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Failed is the worker's verdict on a job that failed. The worker does not decide
// what happens next: the SERVER atomically chooses retry or dead-letter and
// answers with a Result.
type Failed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failed) Reset() {
	*x = Failed{}
	mi := &file_distq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failed) ProtoMessage() {}

func (x *Failed) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failed.ProtoReflect.Descriptor instead.
func (*Failed) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{7}
}

func (x *Failed) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Failed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ServerMessage is everything the server sends down a worker's stream.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_Assigned
	//	*ServerMessage_Result
	//	*ServerMessage_Lost
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_distq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{8}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetAssigned() *Assigned {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Assigned); ok {
			return x.Assigned
		}
	}
	return nil
}

func (x *ServerMessage) GetResult() *Result {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ServerMessage) GetLost() *Lost {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Lost); ok {
			return x.Lost
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Assigned struct {
	Assigned *Assigned `protobuf:"bytes,1,opt,name=assigned,proto3,oneof"`
}

type ServerMessage_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ServerMessage_Lost struct {
	Lost *Lost `protobuf:"bytes,3,opt,name=lost,proto3,oneof"`
}

func (*ServerMessage_Assigned) isServerMessage_Message() {}

func (*ServerMessage_Result) isServerMessage_Message() {}

func (*ServerMessage_Lost) isServerMessage_Message() {}

// Assigned hands this worker a job, with the lease it may hold it for.
type Assigned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	LeaseSeconds  int32                  `protobuf:"varint,2,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assigned) Reset() {
	*x = Assigned{}
	mi := &file_distq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assigned) ProtoMessage() {}

func (x *Assigned) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assigned.ProtoReflect.Descriptor instead.
func (*Assigned) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{9}
}

func (x *Assigned) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *Assigned) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

// Result answers a Completed or Failed report.
type Result struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	JobId   string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Outcome Outcome                `protobuf:"varint,2,opt,name=outcome,proto3,enum=distq.Outcome" json:"outcome,omitempty"`
	// error explains a refused report.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_distq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{10}
}

func (x *Result) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Result) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Lost takes a job away from a worker that stalled past its lease, so it can stop
// working on something that has already been handed to somebody else.
type Lost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lost) Reset() {
	*x = Lost{}
	mi := &file_distq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lost) ProtoMessage() {}

func (x *Lost) ProtoReflect() protoreflect.Message {
	mi := &file_distq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lost.ProtoReflect.Descriptor instead.
func (*Lost) Descriptor() ([]byte, []int) {
	return file_distq_proto_rawDescGZIP(), []int{11}
}

func (x *Lost) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_distq_proto protoreflect.FileDescriptor

const file_distq_proto_rawDesc = "" +
	"\n" +
	"\vdistq.proto\x12\x05distq\"\xb3\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\a \x01(\x05R\n" +
	"maxRetries\".\n" +
	"\x0eEnqueueRequest\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".distq.JobR\x03job\">\n" +
	"\x0fEnqueueResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xcd\x01\n" +
	"\rWorkerMessage\x12$\n" +
	"\x05hello\x18\x01 \x01(\v2\f.distq.HelloH\x00R\x05hello\x120\n" +
	"\theartbeat\x18\x02 \x01(\v2\x10.distq.HeartbeatH\x00R\theartbeat\x120\n" +
	"\tcompleted\x18\x03 \x01(\v2\x10.distq.CompletedH\x00R\tcompleted\x12'\n" +
	"\x06failed\x18\x04 \x01(\v2\r.distq.FailedH\x00R\x06failedB\t\n" +
	"\amessage\"$\n" +
	"\x05Hello\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\"\n" +
	"\tHeartbeat\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\"\n" +
	"\tCompleted\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"D\n" +
	"\x06Failed\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x95\x01\n" +
	"\rServerMessage\x12-\n" +
	"\bassigned\x18\x01 \x01(\v2\x0f.distq.AssignedH\x00R\bassigned\x12'\n" +
	"\x06result\x18\x02 \x01(\v2\r.distq.ResultH\x00R\x06result\x12!\n" +
	"\x04lost\x18\x03 \x01(\v2\v.distq.LostH\x00R\x04lostB\t\n" +
	"\amessage\"M\n" +
	"\bAssigned\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".distq.JobR\x03job\x12#\n" +
	"\rlease_seconds\x18\x02 \x01(\x05R\fleaseSeconds\"_\n" +
	"\x06Result\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12(\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x0e.distq.OutcomeR\aoutcome\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x1d\n" +
	"\x04Lost\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId*~\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OUTCOME_ACCEPTED\x10\x01\x12\x13\n" +
	"\x0fOUTCOME_REFUSED\x10\x02\x12\x14\n" +
	"\x10OUTCOME_RETRYING\x10\x03\x12\x19\n" +
	"\x15OUTCOME_DEAD_LETTERED\x10\x042\x81\x01\n" +
	"\bJobQueue\x128\n" +
	"\aEnqueue\x12\x15.distq.EnqueueRequest\x1a\x16.distq.EnqueueResponse\x12;\n" +
	"\tJobStream\x12\x14.distq.WorkerMessage\x1a\x14.distq.ServerMessage(\x010\x01B(Z&github.com/ss1ngh/distq-go/internal/pbb\x06proto3"

var (
	file_distq_proto_rawDescOnce sync.Once
	file_distq_proto_rawDescData []byte
)

func file_distq_proto_rawDescGZIP() []byte {
	file_distq_proto_rawDescOnce.Do(func() {
		file_distq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distq_proto_rawDesc), len(file_distq_proto_rawDesc)))
	})
	return file_distq_proto_rawDescData
}

var file_distq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_distq_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_distq_proto_goTypes = []any{
	(Outcome)(0),            // 0: distq.Outcome
	(*Job)(nil),             // 1: distq.Job
	(*EnqueueRequest)(nil),  // 2: distq.EnqueueRequest
	(*EnqueueResponse)(nil), // 3: distq.EnqueueResponse
	(*WorkerMessage)(nil),   // 4: distq.WorkerMessage
	(*Hello)(nil),           // 5: distq.Hello
	(*Heartbeat)(nil),       // 6: distq.Heartbeat
	(*Completed)(nil),       // 7: distq.Completed
	(*Failed)(nil),          // 8: distq.Failed
	(*ServerMessage)(nil),   // 9: distq.ServerMessage
	(*Assigned)(nil),        // 10: distq.Assigned
	(*Result)(nil),          // 11: distq.Result
	(*Lost)(nil),            // 12: distq.Lost
}
var file_distq_proto_depIdxs = []int32{
	1,  // 0: distq.EnqueueRequest.job:type_name -> distq.Job
	5,  // 1: distq.WorkerMessage.hello:type_name -> distq.Hello
	6,  // 2: distq.WorkerMessage.heartbeat:type_name -> distq.Heartbeat
	7,  // 3: distq.WorkerMessage.completed:type_name -> distq.Completed
	8,  // 4: distq.WorkerMessage.failed:type_name -> distq.Failed
	10, // 5: distq.ServerMessage.assigned:type_name -> distq.Assigned
	11, // 6: distq.ServerMessage.result:type_name -> distq.Result
	12, // 7: distq.ServerMessage.lost:type_name -> distq.Lost
	1,  // 8: distq.Assigned.job:type_name -> distq.Job
	0,  // 9: distq.Result.outcome:type_name -> distq.Outcome
	2,  // 10: distq.JobQueue.Enqueue:input_type -> distq.EnqueueRequest
	4,  // 11: distq.JobQueue.JobStream:input_type -> distq.WorkerMessage
	3,  // 12: distq.JobQueue.Enqueue:output_type -> distq.EnqueueResponse
	9,  // 13: distq.JobQueue.JobStream:output_type -> distq.ServerMessage
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_distq_proto_init() }
func file_distq_proto_init() {
	if File_distq_proto != nil {
		return
	}
	file_distq_proto_msgTypes[3].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_Completed)(nil),
		(*WorkerMessage_Failed)(nil),
	}
	file_distq_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerMessage_Assigned)(nil),
		(*ServerMessage_Result)(nil),
		(*ServerMessage_Lost)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distq_proto_rawDesc), len(file_distq_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distq_proto_goTypes,
		DependencyIndexes: file_distq_proto_depIdxs,
		EnumInfos:         file_distq_proto_enumTypes,
		MessageInfos:      file_distq_proto_msgTypes,
	}.Build()
	File_distq_proto = out.File
	file_distq_proto_goTypes = nil
	file_distq_proto_depIdxs = nil
}
